const properties = [
  {
    id: 'prop_001',
    title: '3-Bed Semi in Rathfarnham',
    address: '14 Orchard Drive, Rathfarnham, Dublin 14',
    price: 'NPR 1,20,00,000',
    beds: 3,
    baths: 2,
    sqm: 112,
    type: 'Semi-Detached',
  },
  {
    id: 'prop_002',
    title: '2-Bed Apartment, Docklands',
    address: 'Block C, Grand Canal Dock, Dublin 2',
    price: 'NPR 85,00,000',
    beds: 2,
    baths: 1,
    sqm: 78,
    type: 'Apartment',
  },
  {
    id: 'prop_003',
    title: '4-Bed Detached, Sandyford',
    address: '7 The Oaks, Sandyford, Dublin 18',
    price: 'NPR 2,50,00,000',
    beds: 4,
    baths: 3,
    sqm: 185,
    type: 'Detached',
  },
  {
    id: 'prop_004',
    title: '1-Bed Studio, Smithfield',
    address: 'Apt 12, The Mill, Smithfield, Dublin 7',
    price: 'NPR 45,00,000',
    beds: 1,
    baths: 1,
    sqm: 45,
    type: 'Apartment',
  },
  {
    id: 'prop_005',
    title: '3-Bed Terrace, Clontarf',
    address: '23 Vernon Avenue, Clontarf, Dublin 3',
    price: 'NPR 1,80,00,000',
    beds: 3,
    baths: 2,
    sqm: 130,
    type: 'Terraced',
  },
  {
    id: 'prop_006',
    title: '5-Bed Detached, Foxrock',
    address: '2 Brighton Road, Foxrock, Dublin 18',
    price: 'NPR 4,50,00,000',
    beds: 5,
    baths: 4,
    sqm: 260,
    type: 'Detached',
  },
];

module.exports = properties;
